[versions]
kotlin = "1.7.20"
agp = "7.4.2"
ktlint = "10.1.0"
appCompat = "1.3.0"
coreTest = "2.0.0"
coreKtx = "1.3.2"
materialComponents = "1.4.0"
fragment = "1.3.5"
constraintLayout = "2.0.4"
insetter = "0.6.0"
junit = "4.12"
androidxTestCore = "1.2.0"
androidxTestExt = "1.1.1"
androidxTestRunner = "1.2.0"
espressoCore = "3.2.0"
mockk = "1.9.3"
robolectric = "4.3.1"
startup = "1.0.0"
composeActivity = "1.3.1"
composeUi = "1.3.3"
composeCompiler = "1.3.2"
composeFoundation = "1.3.1"
composeMaterial = "1.3.1"
accompanist = "0.28.0"

[libraries]

composeActivity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
composeMaterial = { module = "androidx.compose.material:material", version.ref = "composeMaterial" }
composeTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeUi" }
accompanistSysUi = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanistInsets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
ktlintGradlePlugin = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint" }
kotlinStdLib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
coreTest = { module = "androidx.arch.core:core-testing", version.ref = "coreTest" }
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
materialComponents = { module = "com.google.android.material:material", version.ref = "materialComponents" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
fragmentKtx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
startup = { module = "androidx.startup:startup-runtime", version.ref = "startup" }
insetter = { module = "dev.chrisbanes.insetter:insetter", version.ref = "insetter" }
junit = { module = "junit:junit", version.ref = "junit" }
androidxTestCore = { module = "androidx.test:core", version.ref = "androidxTestCore" }
androidxTestExt = { module = "androidx.test.ext:junit", version.ref = "androidxTestExt" }
androidxTestRunner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }